### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by sealneaward** [nickb1080/nba-movement-demo#1]
This client JSON loading error occurs both in Chrome and Firefox, but Chrome does not continue with the loading. In Firefox, I get this error, but the gameplay will still load.

**Full Error**

```
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at parse (<anonymous>)
    at Array.map (native)
    at http://localhost:4444/bundle.js:80627:16
```

I will look into this and see what I can change in terms of how the JSON is loaded.

**Comment by bttmly** [comment]
how about now on latest master? I had an extra first argument to `res.json` for some unknown reason... I couldn't get it to load at all actually. Seems like it works now in Chrome at least.

**Comment by sealneaward** [comment]
It loads now. Wow. Such a simple fix.

Thanks.

**Comment by bttmly** [comment]
Yea just a typo on my part... not really quite sure how it ever worked 😑

**Comment by bttmly** [comment]
Unfortunately the data format isn't quite compatible with the data from https://github.com/sealneaward/nba-movement-data

This is because originally I was using a [streaming client](https://github.com/nickb1080/nba-movement) to avoid trying to load the data in one large chunk. So this app takes [ndjson](http://ndjson.org/) rather than actual JSON. I'll update that soon (since all the available data is now in full game archived chunks) so it'll interop with `nba-movement-data` easily.
